package codesmell;

public enum CodeSmellId {

	COMPLEX_METHOD, GOD_CLASS, LONG_METHOD, DATA_CLASS, FEATURE_ENVY,LARGE_CLASS,PRIMITIVE_OBSESSION,LONG_PARAMETER_LIST,LAZY_CLASS,SWITCH_STATEMENT;

}